add docs to main workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -5,10 +5,11 @@ on: [push, pull_request]
 
 jobs:
   build:
+    name: Build and test
     runs-on: ubuntu-20.04 # required for latest QuantLib
     strategy:
       matrix:
-        python-version: ['3.6', '3.7', '3.8']
+        python-version: ['3.7', '3.8', '3.9']
 
     steps:
       - name: install dependencies
@@ -44,3 +45,45 @@ jobs:
       - name: Run tests
         run: |
            python -m unittest discover -v
+
+      # Publish built docs to gh-pages branch.
+      - name: Checkout documentation branch
+        if: matrix.python-version == '3.9'
+        uses: actions/checkout@v2
+        with:
+          ref: gh-pages
+          path: gh-pages
+          persist-credentials: false
+
+      - name: Build docs
+        if: matrix.python-version == '3.9'
+        run: |
+          pip install sphinx
+          make docs
+
+      - uses: actions/upload-artifact@v2
+        if: (matrix.python-version == '3.9') && (github.event_name == 'pull_request')
+        with:
+          name: "doc_${{ github.event.pull_request.number }}"
+          path: docs/build/html
+
+      - name: Move docs over
+        if: (matrix.python-version == 3.9) && (github.event_name == 'push')
+        run: |
+          ls
+          cp -r docs/build/html/* gh-pages/
+          cd gh-pages
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add .
+          git commit -m "New documentation" -a || true
+          # The above command will fail if no changes were present, so we ignore
+          # that.
+
+      - name: Push changes
+        if: (matrix.python-version == '3.9') && (github.event_name== 'push')
+        uses: ad-m/github-push-action@master
+        with:
+          branch: gh-pages
+          directory: gh-pages
+          github_token: ${{ secrets.GITHUB_TOKEN }}
